---
- hosts: aws
  remote_user: "{{ init_user }}"
  become: yes
  tasks:
    - name: Copy primary user authorized_keys to root
      shell: "cp /home/{{ init_user }}/.ssh/authorized_keys /root/.ssh/"

...